name: CD

on:
  push:
    branches: main
    tags: '**'
    paths-ignore:
      - 'demos/**'
      - 'tests/**'

jobs:
  Pack:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - run: dotnet pack -c Release -p:PackageOutputPath=../../nuget -p:Version=$VERSION
      - uses: actions/upload-artifact@v3
        with:
          name: NuGet
          path: ./nuget
  Publish:
    runs-on: ubuntu-latest
    needs: Pack
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - uses: actions/download-artifact@v3
        with:
          name: NuGet
          path: ./nuget
      - run: dotnet nuget push ./nuget/**.nupkg --source nuget.org --api-key ${{secrets.NUGET_API_KEY}}
