name: CD

on:
  workflow_run:
    workflows: CI
    branches: main
    types:
      - completed

jobs:
  Pack:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - run: dotnet pack -c Release -p:PackageOutputPath=../../nuget -p:Version=$VERSION
      - uses: actions/upload-artifact@v3
        with:
          name: NuGet
          path: ./nuget
