name: CI

on:
  push:
    branches: [ '*' ]
    paths-ignore:
      - 'demos/**'

jobs:
  Run_Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6.0.x', '7.0.x' ]
    name: .NET ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet test
  Pack:
    runs-on: ubuntu-latest
    needs: Run_Tests
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
      - run: dotnet pack -o ./nuget -c Release -p:Version=$VERSION
      - uses: actions/upload-artifact@v3
        with:
          name: NuGet
          path: ./nuget
