name: CI

on:
  push:
    branches: [ '*' ]
    paths-ignore:
      - 'demos/**'

jobs:
  Run_Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6.0.x', '7.0.x' ]
    name: .NET ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet test
